# This file was generated by GoReleaser. DO NOT EDIT.
cask "jenkins-job-cli" do
  name "jenkins-job-cli"
  desc "Jenkins CLI tool for managing Jenkins jobs programmatically"
  homepage "https://github.com/jeffzhangc/jenkins-job-cli"
  version "1.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jenkins-job-cli"
  bash_completion "completions/jj.bash"
  zsh_completion "completions/jj.zsh"
  fish_completion "completions/jj.fish"

  on_macos do
    on_intel do
      url "https://github.com/jeffzhangc/jenkins-job-cli/releases/download/v#{version}/jenkins-job-cli_Darwin_x86_64.tar.gz",
        verified: "github.com/jeffzhangc/jenkins-job-cli/download"
      sha256 "d578240a3230a593239b669376cf95785956a7ab585aef10666bc82732f5e19e"
    end
    on_arm do
      url "https://github.com/jeffzhangc/jenkins-job-cli/releases/download/v#{version}/jenkins-job-cli_Darwin_arm64.tar.gz",
        verified: "github.com/jeffzhangc/jenkins-job-cli/download"
      sha256 "7dba2a4438cb5d866e74c2d93bdb76c9ca9217f2b002102e01d42ad0aa581a44"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jeffzhangc/jenkins-job-cli/releases/download/v#{version}/jenkins-job-cli_Linux_x86_64.tar.gz",
        verified: "github.com/jeffzhangc/jenkins-job-cli/download"
      sha256 "64a8a13f9671dcf6cd39b517cb41755f1f614438d81405fc1746a8111e4f8d64"
    end
    on_arm do
      url "https://github.com/jeffzhangc/jenkins-job-cli/releases/download/v#{version}/jenkins-job-cli_Linux_arm64.tar.gz",
        verified: "github.com/jeffzhangc/jenkins-job-cli/download"
      sha256 "5b3a83c090740c4d6b819a8a45569d734f70e641fbbf8e2cc66f798d5e32f206"
    end
  end

  postflight do
    brew_prefix = ENV['HOMEBREW_PREFIX'] || '/opt/homebrew'
    target = "#{brew_prefix}/bin/jj"
    binary_path = "#{staged_path}/jenkins-job-cli"

    # Remove quarantine attribute
    system_command '/usr/bin/xattr',
                   args: ['-d', 'com.apple.quarantine', binary_path]

    # Create symlink
    system_command '/bin/ln',
                   args: ['-sf', binary_path, target],
                   sudo: true
  end

  caveats do
    "To use the CLI, run:"
    "  jj --help"
    ""
    "To enable shell completions:"
    "  echo 'source <(jj completion zsh)' >>~/.zshrc  # for zsh"
    "  echo 'source <(jj completion bash)' >>~/.bashrc # for bash"
  end

  uninstall trash: [
      "~/.jj",
    ]

  # No zap stanza required
end
