# This file was generated by GoReleaser. DO NOT EDIT.
cask "jenkins-job-cli" do
  name "jenkins-job-cli"
  desc "jenkins cli , simplified"
  homepage "https://github.com/jeffzhangc/jenkins-job-cli"
  version "1.2.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jj"
  bash_completion "completions/jj.bash"
  zsh_completion "completions/jj.zsh"
  fish_completion "completions/jj.fish"

  on_macos do
    on_intel do
      url "https://github.com/jeffzhangc/jenkins-job-cli/releases/download/v#{version}/jenkins-job-cli_Darwin_x86_64.tar.gz",
        verified: "github.com/jeffzhangc/jenkins-job-cli/download"
      sha256 "61a7d20ad05aadf4837d0429b11ceaea90d2cac9b592c100f3e599025f0bbc08"
    end
    on_arm do
      url "https://github.com/jeffzhangc/jenkins-job-cli/releases/download/v#{version}/jenkins-job-cli_Darwin_arm64.tar.gz",
        verified: "github.com/jeffzhangc/jenkins-job-cli/download"
      sha256 "5e89d4cde12f6f6708feaf0c39c94bae720245ffc95fa6687d803494eb318adf"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jeffzhangc/jenkins-job-cli/releases/download/v#{version}/jenkins-job-cli_Linux_x86_64.tar.gz",
        verified: "github.com/jeffzhangc/jenkins-job-cli/download"
      sha256 "f4e3ce39363a59f4b7b83755b03e1772b28c847df6f9dee9649740bf85c4bacb"
    end
    on_arm do
      url "https://github.com/jeffzhangc/jenkins-job-cli/releases/download/v#{version}/jenkins-job-cli_Linux_arm64.tar.gz",
        verified: "github.com/jeffzhangc/jenkins-job-cli/download"
      sha256 "65ad7ebd0cf50c0c660d32be437f42bcfae189b912e5275f1bf106ff52bb9dd1"
    end
  end

  caveats do
    "jj help"
  end

  uninstall trash: [
      "~/.jj",
    ]

  # No zap stanza required
end
