# This file was generated by GoReleaser. DO NOT EDIT.
cask "jenkins-job-cli" do
  name "jenkins-job-cli"
  desc "jenkins cli , simplified"
  homepage "https://github.com/jeffzhangc/jenkins-job-cli"
  version "1.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jenkins-job-cli"
  bash_completion "completions/jj.bash"
  zsh_completion "completions/jj.zsh"
  fish_completion "completions/jj.fish"

  on_macos do
    on_intel do
      url "https://github.com/jeffzhangc/jenkins-job-cli/releases/download/v#{version}/jenkins-job-cli_Darwin_x86_64.tar.gz",
        verified: "github.com/jeffzhangc/jenkins-job-cli/download"
      sha256 "77a60719ac7a19fe990ba903377d62c3e0f5535858c0452f1452b04c4c95cd73"
    end
    on_arm do
      url "https://github.com/jeffzhangc/jenkins-job-cli/releases/download/v#{version}/jenkins-job-cli_Darwin_arm64.tar.gz",
        verified: "github.com/jeffzhangc/jenkins-job-cli/download"
      sha256 "316d85b70aeef30ceb7ec409335ea17fed4c56d990a4b81ab11ea215647f1413"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jeffzhangc/jenkins-job-cli/releases/download/v#{version}/jenkins-job-cli_Linux_x86_64.tar.gz",
        verified: "github.com/jeffzhangc/jenkins-job-cli/download"
      sha256 "4eef9cb80fbe864d7bbe8d0c3cabfa125be9f7dab93ca08f5f7bf86b058b0593"
    end
    on_arm do
      url "https://github.com/jeffzhangc/jenkins-job-cli/releases/download/v#{version}/jenkins-job-cli_Linux_arm64.tar.gz",
        verified: "github.com/jeffzhangc/jenkins-job-cli/download"
      sha256 "e826f27d2a9b91ef93635d4d24e6ca61637ff790f47f1827d09427f90d4984fb"
    end
  end

  postflight do
    target = if Hardware::CPU.arm?
      '/opt/homebrew/bin/jj'
    else
      '/usr/local/bin/jj'
    end
    system_command '/bin/ln',
                  args: ['-sf', "#{staged_path}/jenkins-job-cli", target],
                  sudo: true
  end

  caveats do
    "jj help"
  end

  uninstall trash: [
      "~/.jj",
    ]

  # No zap stanza required
end
