# This file was generated by GoReleaser. DO NOT EDIT.
cask "sshpky" do
  name "sshpky"
  desc "ssh tools , simplified"
  homepage "https://github.com/jeffzhangc/go-sshpky"
  version "2.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sshpky"
  bash_completion "completions/sshpky.bash"
  zsh_completion "completions/sshpky.zsh"
  fish_completion "completions/sshpky.fish"

  on_macos do
    on_intel do
      url "https://github.com/jeffzhangc/go-sshpky/releases/download/#{version}/go-sshpky_Darwin_x86_64.tar.gz",
        verified: "github.com/jeffzhangc/go-sshpky/download"
      sha256 "aec97c63302d2a2cf000e977c509293f5b880ec3d46454833e99c2be4bc2e7fc"
    end
    on_arm do
      url "https://github.com/jeffzhangc/go-sshpky/releases/download/#{version}/go-sshpky_Darwin_arm64.tar.gz",
        verified: "github.com/jeffzhangc/go-sshpky/download"
      sha256 "d6dcdf78546bdedd9fade2499a559d65c346ef983fed6f991fc2f9d594c79ab4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jeffzhangc/go-sshpky/releases/download/#{version}/go-sshpky_Linux_x86_64.tar.gz",
        verified: "github.com/jeffzhangc/go-sshpky/download"
      sha256 "07183b978d6ee9c0bcf7bd5026d69c911f3b21d9f7162aaa795835c8adfc97d6"
    end
    on_arm do
      url "https://github.com/jeffzhangc/go-sshpky/releases/download/#{version}/go-sshpky_Linux_arm64.tar.gz",
        verified: "github.com/jeffzhangc/go-sshpky/download"
      sha256 "44d8e9a6d6f4958bd4ff65ddad1bfab9c15f0ba8942f98d6a0cb13830f8e85bb"
    end
  end

  caveats do
    "sshpky help"
  end

  uninstall trash: [
      "~/.sshpky",
    ]

  # No zap stanza required
end
