# This file was generated by GoReleaser. DO NOT EDIT.
cask "sshpky" do
  name "sshpky"
  desc "ssh tools , simplified"
  homepage "https://github.com/jeffzhangc/go-sshpky"
  version "2.3.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sshpky"
  bash_completion "completions/sshpky.bash"
  zsh_completion "completions/sshpky.zsh"
  fish_completion "completions/sshpky.fish"

  on_macos do
    on_intel do
      url "https://github.com/jeffzhangc/go-sshpky/releases/download/v#{version}/go-sshpky_Darwin_x86_64.tar.gz",
        verified: "github.com/jeffzhangc/go-sshpky/download"
      sha256 "b2725fcd56797f86548ecf7c1d467bda4e430414c8bf0f9a1cd53814ab50598c"
    end
    on_arm do
      url "https://github.com/jeffzhangc/go-sshpky/releases/download/v#{version}/go-sshpky_Darwin_arm64.tar.gz",
        verified: "github.com/jeffzhangc/go-sshpky/download"
      sha256 "eb1c499d8d94ceba3531ab5f70f8828c1e4e52ae8f353fa0250e87b99b5f5f69"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jeffzhangc/go-sshpky/releases/download/v#{version}/go-sshpky_Linux_x86_64.tar.gz",
        verified: "github.com/jeffzhangc/go-sshpky/download"
      sha256 "dee622940aa77143dfe9f39109b761636a083d92880c09439769da7959959df6"
    end
    on_arm do
      url "https://github.com/jeffzhangc/go-sshpky/releases/download/v#{version}/go-sshpky_Linux_arm64.tar.gz",
        verified: "github.com/jeffzhangc/go-sshpky/download"
      sha256 "b2d83116f439a43b542d5b42a7a759c5e63a4df3b717a8305d4eae30269636e5"
    end
  end

  caveats do
    "sshpky help"
    ""
    "Note: Configuration files are stored in ~/.sshpky. You can remove this directory if you want to completely uninstall all configuration data."
  end

  # No zap stanza required
end
