# This file was generated by GoReleaser. DO NOT EDIT.
cask "sshpky" do
  name "sshpky"
  desc "ssh tools , simplified"
  homepage "https://github.com/jeffzhangc/go-sshpky"
  version "2.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sshpky"
  bash_completion "completions/sshpky.bash"
  zsh_completion "completions/sshpky.zsh"
  fish_completion "completions/sshpky.fish"

  on_macos do
    on_intel do
      url "https://github.com/jeffzhangc/go-sshpky/releases/download/#{version}/go-sshpky_Darwin_x86_64.tar.gz",
        verified: "github.com/jeffzhangc/go-sshpky/download"
      sha256 "08da805fc1faf2b6801c4f74076a707434789db32db2e27f1a256983bbb8b6d1"
    end
    on_arm do
      url "https://github.com/jeffzhangc/go-sshpky/releases/download/#{version}/go-sshpky_Darwin_arm64.tar.gz",
        verified: "github.com/jeffzhangc/go-sshpky/download"
      sha256 "fcb4575d3e4d82aa96366c25f708581a8b242d364c95e9be4299e185682f4fd6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jeffzhangc/go-sshpky/releases/download/#{version}/go-sshpky_Linux_x86_64.tar.gz",
        verified: "github.com/jeffzhangc/go-sshpky/download"
      sha256 "4fdf45d95425dc7d46a0988bef5ed61daa334f196e51f0633e7466e479fdcd0b"
    end
    on_arm do
      url "https://github.com/jeffzhangc/go-sshpky/releases/download/#{version}/go-sshpky_Linux_arm64.tar.gz",
        verified: "github.com/jeffzhangc/go-sshpky/download"
      sha256 "c44b7a7377cb26c9497920c56dacc0dea3cf5d54ec2010da5e38c8453bb11d47"
    end
  end

  caveats do
    "sshpky help"
  end

  uninstall trash: [
      "~/.sshpky",
    ]

  # No zap stanza required
end
