# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JenkinsJobCli < Formula
  desc "Jenkins job CLI tool"
  homepage "https://github.com/jeffzhangc/jenkins-job-cli"
  version "1.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jeffzhangc/jenkins-job-cli/releases/download/v1.2.3/jenkins-job-cli_1.2.3_darwin_amd64.tar.gz"
      sha256 "5f0eb6cb62852d92c42aaae0048289a77999cba5b9a68c473a1b2205782d0776"

      def install
        bin.install "jenkins-job-cli"
        bin.install_symlink "jenkins-job-cli" => "jj"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jeffzhangc/jenkins-job-cli/releases/download/v1.2.3/jenkins-job-cli_1.2.3_linux_arm64.tar.gz"
      sha256 "9da5b15cb6ada4e72c8e46b29bfa1eb457f71e03132ed735c71be193c9329a99"

      def install
        bin.install "jenkins-job-cli"
        bin.install_symlink "jenkins-job-cli" => "jj"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jeffzhangc/jenkins-job-cli/releases/download/v1.2.3/jenkins-job-cli_1.2.3_linux_amd64.tar.gz"
      sha256 "bc0307b618593c2df50de453f6f332f6f9a7616c78184a42a6334a9403bd5ad1"

      def install
        bin.install "jenkins-job-cli"
        bin.install_symlink "jenkins-job-cli" => "jj"
      end
    end
  end

  def caveats; <<~EOS
    You can use either 'jenkins-job-cli' or 'jj' command
  EOS
  end

  test do
    system "#{bin}/jenkins-job-cli --version"
    system "#{bin}/jj --version"
  end
end
